### ISSUE TITLE
Caltech Birds Dataset

### ISSUE THREAD

**Issue by alexander-g** [talreiss/PANDA#1]
Thank you for uploading. The code is well written and readable and I was able to reproduce the CIFAR10 results.

I am more interested in fine-grained datasets, as you reported in your paper in table 2. I have created a [fork](https://github.com/alexander-g/PANDA) and added the Caltech Birds dataset ([diff](https://github.com/alexander-g/PANDA/commit/a6b08491aeeb555d2ee8f4c878c6f03293ea04cc)). I am using the first 20 classes as normal classes and the entire test set for evaluation as mentioned in appendix C. However, I am not able to reproduce your results. I only get an initial AUROC value of 76.9% and this gets worse during training, with and without `--ewc`. This is still higher than the compared methods but much lower than the reported 95.3%.

Could you please take a look and see what/if I got something wrong, or maybe you could also provide your code for the datasets in table 2?

**Comment by NivC** [comment]
Thanks! We are happy to hear that you found it useful.

I ran again Caltech Birds on our end, and was able to reproduce the results. Please recheck the labels assigned to each class, the class sizes, etc.

We do not claim in the paper that ewc improves results for small datasets (e.g. Caltech Birds). We actually did find that after very long training, a small improvement is possible for some classes of small datasets.

**Comment by eladmeir** [comment]
Sorry to re-open this issue, but I am not sure that I have understood the use of Birds (and Flowers) datasets

When stating "...the first 20 classes as normal train set, and using the entire test set for evaluation.", do you mean that:
The assemble of first (by what order) 20 classes are defined as "normal" class, while the rest of classes are defined as "abnormal"? 

If this is not the case, can you please elaborate?

**Comment by NivC** [comment]
No. For each of the 20 first classes we evaluated that single class as normal and all the rest as anomalies (during test time). For average score, we averaged over these 20 classes.
