### ISSUE TITLE
About results of SPADE on MVTec 

### ISSUE THREAD

**Issue by zhangjieTHU** [talreiss/PANDA#11]
Dear authors,
Thank you for your excellent work. I am slightly confused about the SPADE method and its results on MVTec.
In Table 4, you reported the segmentation AUROC and PRO of 96.2 and 91.7. However, in Table 8, you reported the PRO value of 97.3, which I think is impossible and 97.3 doesn't match any metric reported in the paper. 
You compared cat and ensemble methods for SPADE and it seems the ensemble method improved 0.2 AUROC scores for segmentation, according to the previous arxiv version https://arxiv.org/pdf/2005.02357.pdf. However, you changed the kernel size of Gaussian filter from 4 to 5 and I am not sure about the influence of this change.
Also, as the images were resized to 256 and then cropped to 224, why metrics were still calculated at 256×256 image resolution? Will this setting improve the segmentation performance?
I am looking forward to your reply and thank you in advance!

**Comment by zhangjieTHU** [comment]
And one more question, about the size of the memory bank. In the previous arxiv version, 50 nearest normal images are used to build the feature gallery, did you still apply this setting in PANDA paper? Thank you!

**Comment by NivC** [comment]
Dear Jie Zhang,

Thank you for your question and your interest in our work!

It seems that table 8 (table 2 in the supplementary material), reports ROC-AUC and not PRO as mentioned. We apologize for the confusion and will check if this can be clarified in the conference version of the manuscript. Thank you for noticing it!

The metric should generally not depend on the resolution in which it is calculated (up to a very small numerical error). The difference between the reported score and the ROC-AUC in the arXiv version follows from the different implementation details. Most importantly, we do not use only the 50 nearest normal images for the memory bank, but all of them (as you noticed).

Best regards,
Niv.

P.S.
You can find a reimplementation of our segmentation method described in the arXiv paper here:
https://github.com/byungjae89/SPADE-pytorch

**Comment by zhangjieTHU** [comment]
Dear Niv,
Thank you for your quick and detailed reply!
