### ISSUE TITLE
Could you provide the Fisher Matrix for resnet18 and resnet 34?

### ISSUE THREAD

**Issue by secretfish2000** [talreiss/PANDA#12]
Thank you for a job well done！
Only the Fisher Matrix of ResNet152 is available in the codebase,could you please provide the Fisher Matrix for resnet18 and resnet 34. Calculating this result myself requires a lot of memory.

**Comment by talreiss** [comment]
Hi,

Unfortunately, we do not have fisher matrix weights for other backbones.

**Comment by caiyu6666** [comment]
Hi. I wonder whether you calculated the Fisher Matrix for Resnet18 and 34 successfully? Thanks!

**Comment by secretfish2000** [comment]
> Hi. I wonder whether you calculated the Fisher Matrix for Resnet18 and 34 successfully? Thanks!

I didn't do the math.
