### ISSUE TITLE
Questions about loss increasement

### ISSUE THREAD

**Issue by caiyu6666** [talreiss/PANDA#14]
Hi, thanks for your excellent work! I have a question to confirm.

During training on some datasets, I observe that both loss values and AUROC increase. I am wondering whether this phenomenon is reasonable. Could you please help explain it?

Thanks a lot!

**Comment by talreiss** [comment]
This is due to the fact that the model tries to force compactness in the feature space while also not straying too far from the original pretrained data. It can sometimes cause the phenomenon that you have described.
