### ISSUE TITLE
Question about center update

### ISSUE THREAD

**Issue by Youskrpig** [talreiss/PANDA#5]
Hi, two more questions. Why not update center(torch.FloatTensor(feature_space).mean(dim=0)) of criterion during training? why the training loss is increasing no matter which dataset i use for training?

**Comment by Youskrpig** [comment]
Here is my cifar10 result(class 0 for training):
Epoch: 0, AUROC is: 0.8745607777777777
Epoch: 0, train_feature_center is: 0.31425341963768005
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 1, Loss: 0.1202019146008856
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.24it/s]
Test set feature extracting: 100%|██████████| 313/313 [00:59<00:00,  5.24it/s]
Epoch: 1, AUROC is: 0.8770826111111112
Epoch: 2, Loss: 0.1417769790170299
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.22it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.18it/s]
Epoch: 2, AUROC is: 0.8787223888888889
Epoch: 3, Loss: 0.17976626402633206
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.24it/s]
Test set feature extracting: 100%|██████████| 313/313 [00:59<00:00,  5.22it/s]
Epoch: 3, AUROC is: 0.8797657222222222
Epoch: 4, Loss: 0.2334675378860182
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.24it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.21it/s]
Epoch: 4, AUROC is: 0.8805781111111111
Epoch: 5, Loss: 0.30255350831207956
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.24it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.20it/s]
Epoch: 5, AUROC is: 0.8812161666666667
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 6, Loss: 0.38657432225099797
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.24it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.18it/s]
Epoch: 6, AUROC is: 0.8817392222222222
Epoch: 7, Loss: 0.48555853184621045
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.23it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.19it/s]
Epoch: 7, AUROC is: 0.8821664444444445
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 8, Loss: 0.5994999993378949
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.23it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.18it/s]
Epoch: 8, AUROC is: 0.8825364444444443
Epoch: 9, Loss: 0.7279898930507102
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.23it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.18it/s]
Epoch: 9, AUROC is: 0.8828858333333334
Epoch: 10, Loss: 0.8713807289008122
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  5.05it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:04<00:00,  4.88it/s]
Epoch: 10, AUROC is: 0.8831851111111111
Epoch: 11, Loss: 1.0294302667781805
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  5.00it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.16it/s]
Epoch: 11, AUROC is: 0.8834594444444445
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 12, Loss: 1.2020608163942956
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  4.97it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:04<00:00,  4.88it/s]
Epoch: 12, AUROC is: 0.8836706666666667
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 13, Loss: 1.3893892309468263
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  4.93it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:04<00:00,  4.84it/s]
Epoch: 13, AUROC is: 0.8838659444444443
Epoch: 14, Loss: 1.59125983031692
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  4.93it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:04<00:00,  4.87it/s]
Epoch: 14, AUROC is: 0.8840281111111112
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 15, Loss: 1.8075437135757155
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  4.97it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:03<00:00,  4.90it/s]
Epoch: 15, AUROC is: 0.8841785555555556
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 16, Loss: 2.0383165626768855
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  5.04it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:02<00:00,  4.97it/s]
Epoch: 16, AUROC is: 0.8843057777777777
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 17, Loss: 2.2835414379265657
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  4.96it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:03<00:00,  4.95it/s]
Epoch: 17, AUROC is: 0.884411111111111
Epoch: 18, Loss: 2.5432277287647223
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.09it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.08it/s]
Epoch: 18, AUROC is: 0.8845087222222223
Epoch: 19, Loss: 2.8171097442602657
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.20it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.10it/s]
Epoch: 19, AUROC is: 0.8846011666666667
Epoch: 20, Loss: 3.105325061044875
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.19it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.08it/s]
Epoch: 20, AUROC is: 0.8846327777777778
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 21, Loss: 3.407728126853894
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.08it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.10it/s]
Epoch: 21, AUROC is: 0.8846894444444444
Epoch: 22, Loss: 3.724537323994242
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.20it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 22, AUROC is: 0.884739611111111
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 23, Loss: 4.055365747706905
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.21it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.09it/s]
Epoch: 23, AUROC is: 0.8847577777777778
Epoch: 24, Loss: 4.400328821437374
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.18it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 24, AUROC is: 0.8847642222222222
Epoch: 25, Loss: 4.759392613817932
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.07it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.08it/s]
Epoch: 25, AUROC is: 0.884775388888889
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 26, Loss: 5.132577206678452
Train set feature extracting: 100%|██████████| 157/157 [00:32<00:00,  4.85it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:02<00:00,  4.99it/s]
Epoch: 26, AUROC is: 0.8847713333333334
Epoch: 27, Loss: 5.51961055379005
Train set feature extracting: 100%|██████████| 157/157 [00:31<00:00,  5.06it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:02<00:00,  5.04it/s]
Epoch: 27, AUROC is: 0.8847716111111111
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 28, Loss: 5.920700799128053
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.18it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.09it/s]
Epoch: 28, AUROC is: 0.8847412222222223
Epoch: 29, Loss: 6.335707567300007
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.10it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.09it/s]
Epoch: 29, AUROC is: 0.8847025
Epoch: 30, Loss: 6.764595994524136
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.17it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.05it/s]
Epoch: 30, AUROC is: 0.8846480555555557
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 31, Loss: 7.207365713301738
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.19it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 31, AUROC is: 0.8845648888888888
Epoch: 32, Loss: 7.663962658803174
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.15it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.05it/s]
Epoch: 32, AUROC is: 0.8844814999999999
Epoch: 33, Loss: 8.134562957059046
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.21it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.08it/s]
Epoch: 33, AUROC is: 0.8843834444444444
Epoch: 34, Loss: 8.61862175935393
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.20it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.08it/s]
Epoch: 34, AUROC is: 0.8842827222222223
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 35, Loss: 9.116525698619284
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.18it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.10it/s]
Epoch: 35, AUROC is: 0.8841693888888889
Epoch: 36, Loss: 9.628116686632678
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.20it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.14it/s]
Epoch: 36, AUROC is: 0.8840238333333332
Epoch: 37, Loss: 10.153451597614653
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.22it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 37, AUROC is: 0.8839075
Epoch: 38, Loss: 10.692313467621045
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.22it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 38, AUROC is: 0.8837463333333333
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 39, Loss: 11.244788698330048
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.21it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.11it/s]
Epoch: 39, AUROC is: 0.8835456666666667
Epoch: 40, Loss: 11.810919397196193
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.22it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.14it/s]
Epoch: 40, AUROC is: 0.8833534444444445
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 41, Loss: 12.39050930168978
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.20it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 41, AUROC is: 0.8831449444444444
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 42, Loss: 12.983652776973262
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.21it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.09it/s]
Epoch: 42, AUROC is: 0.8829168333333333
Epoch: 43, Loss: 13.590252827686868
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.23it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 43, AUROC is: 0.8826807222222223
Epoch: 44, Loss: 14.210223477357513
Train set feature extracting: 100%|██████████| 157/157 [00:29<00:00,  5.24it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.15it/s]
Epoch: 44, AUROC is: 0.8824082777777777
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 45, Loss: 14.843580810887039
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.23it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:00<00:00,  5.17it/s]
Epoch: 45, AUROC is: 0.8821458888888889
Epoch: 46, Loss: 15.490202229493743
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.23it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.09it/s]
Epoch: 46, AUROC is: 0.8818762222222223
Epoch: 47, Loss: 16.15030719975757
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.21it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.06it/s]
Epoch: 47, AUROC is: 0.8815872222222222
Epoch: 48, Loss: 16.823680719752222
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.19it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.12it/s]
Epoch: 48, AUROC is: 0.8813026666666666
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 49, Loss: 17.510339809830782
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.17it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.05it/s]
Epoch: 49, AUROC is: 0.8810329444444445
Train set feature extracting:   0%|          | 0/157 [00:00<?, ?it/s]Epoch: 50, Loss: 18.210082983515065
Train set feature extracting: 100%|██████████| 157/157 [00:30<00:00,  5.18it/s]
Test set feature extracting: 100%|██████████| 313/313 [01:01<00:00,  5.06it/s]
Epoch: 50, AUROC is: 0.8807547777777778

The AUROC increase and then almost stay still.
And i plot the feature space every epoch during training. 
![image](https://user-images.githubusercontent.com/51428142/127647306-5c3609d8-1d42-4d4e-a9fd-4811bc3f03a4.png)
The blue points represents 0 class samples in test data. The red points represents other classes samples in test data. 
The cyan points represents 0 class samples in train data. Because of large amount of samples, i choose 500 test samples and 300 train samples for visualizing By TSNE. 
Although AUROC increase，but loss also increase. And it seems that the process of feature adaption not so good (no clear compactness) from 50 pictures.

**Comment by NivC** [comment]
1. "Why not update center(torch.FloatTensor(feature_space).mean(dim=0)) of criterion during training?"
You are welcome to try. From our experience this kind of changes did not influence the results much.

2. I ran our code again. It seems that our loss decreases..

[fa_env] <10|1>nivc@dumfries-003:/cs/labs/peleg/nivc/ATLAS/PANDA% python panda.py --dataset=cifar10 --label=0
Dataset: cifar10, Normal Label: 0, LR: 0.01
cuda:0
Files already downloaded and verified
Files already downloaded and verified
Train set feature extracting: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:14<00:00, 10.91it/s]
Test set feature extracting: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:27<00:00,  3.58it/s]
Epoch: 0, AUROC is: 0.9390227777777778
Epoch: 1, Loss: 0.11216305229504397
Train set feature extracting: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:14<00:00, 10.77it/s]
Test set feature extracting: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:28<00:00,  3.55it/s]
Epoch: 1, AUROC is: 0.9423284444444444
Epoch: 2, Loss: 0.09556648785331447
Train set feature extracting: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:14<00:00, 10.72it/s]
Test set feature extracting: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:28<00:00,  3.54it/s]
Epoch: 2, AUROC is: 0.9475472222222222

I am not sure which data do you use, but you can try reducing the learning rate.

**Comment by shdalton** [comment]
Hi NivC,

I can indeed duplicate your results but keeping it all the same while adding the --ewc parameter on the command line gives me results very similar to Youskrpig... what am I missing? I'd expect the loss to go down even with ewc activated...

**Comment by NivC** [comment]
Hi,

As I mentioned earlier, running the publish code as "python panda.py --dataset=cifar10 --label=0
Dataset: cifar10, Normal Label: 0, LR: 0.01" indeed decreased the loss when I tried it.

I am not sure what I can recommend here beyond trying to run it as published as making sure you use the dataloader correctly.
