### ISSUE TITLE
Would U like to release the code about anomaly segmentation?

### ISSUE THREAD

**Issue by tomFoxxxx** [talreiss/PANDA#6]
Thanks a lot!

**Comment by NivC** [comment]
Hi,

Thanks for your interest. 

We plan on adding it. Anyhow, you can meanwhile check:
https://github.com/byungjae89/SPADE-pytorch

Which gives similar results to ours (not sure about the runtime though).

Niv.

**Comment by tomFoxxxx** [comment]
> Hi,
> 
> Thanks for your interest.
> 
> We plan on adding it. Anyhow, you can meanwhile check:
> https://github.com/byungjae89/SPADE-pytorch
> 
> Which gives similar results to ours (not sure about the runtime though).
> 
> Niv.

Thanks!  Your work is excellent and really helps me a lot.

**Comment by NivC** [comment]
Happy to hear that :-)
