### ISSUE TITLE
performance of mvtec

### ISSUE THREAD

**Issue by bartproo** [talreiss/PANDA#7]
Hi, do u have the anomaly detection performance (image-level) of PANDA on Mvtec Dataset ?

**Comment by bartproo** [comment]
Also i wonder in the paper Modeling the Distribution of Normal Data in Pre-Trained Deep Features for Anomaly Detection, the performance was quite good. Have u tried with mahalanobis distance instead of NN?

**Comment by NivC** [comment]
Hi,

These are the results with DN2 (no adaptation):

| Class      |  Roc AUC |
|------------|----------|
|   Bottle   |   97.9   |
|    Cable   |   86.1   |
|   Capsule  |   87.5   |
|   Carpet   |   88.2   |
|    Grid    |    54    |
|  Hazelnut  |   96.9   |
|   Leather  |   97.9   |
|  Metal Nut |   80.9   |
|    Pill    |    79    |
|    Screw   |   66.9   |
|    Tile    |   98.7   |
| Toothbrush |   84.4   |
| Transistor |   91.1   |
|    Wood    |   94.7   |
|   Zipper   |   93.2   |
|   Average  |   86.5   |

Adaptation can do some good also here, but while we do not report it, you are most welcome to try :-)

Regarding the second question:
We have tried it. It gives nice results, but not better than PANDA on most datasets. Linear whitening of the features + kNN is also a strong method, combining the strength of linear feature adaption and kNN scoring. On larger datasets  PANDA performs better, but linear whitening/mahalanobis might be better for small ones.

You might want to check out this paper as well:
https://arxiv.org/pdf/2106.08265.pdf
