### ISSUE TITLE
Detailed ROCAUC performance of each class on CIFAR10

### ISSUE THREAD

**Issue by TabGuigui** [talreiss/PANDA#8]
Hi, do u have the detailed anomaly detection performance of each class on CIFAR10 Dataset Of PANDA method?

**Comment by NivC** [comment]
Sure:

97.42
98.44
93.89
90.55
97.48
94.42
97.53
97.53
97.64
97.44
Avg
96.23

Classes are ordered as used in the script.

**Comment by TabGuigui** [comment]
> Sure:
> 
> 97.42 98.44 93.89 90.55 97.48 94.42 97.53 97.53 97.64 97.44 Avg 96.23
> 
> Classes are ordered as used in the script.

Thank you so much. What's more, is there a detailed cifar100 dataset process code or reference?
